language: python
sudo: false

env:
  global:
    # Doctr deploy key for yeatmanlab/AFQ-Browser
    - secure: "oW7K+0NItX66DI0/QGtjMZ/wdmWnddIZ6ve0BAR5Bq7rKFXXO1muWupyG95uiOZ9NQ9tE0iTsosGQ+bBcD4O97jTpQkwuML4nOGYwXpWbhgd4rjtMJ2wWrCnI/AtW2jlzYJ9aGmek78t+tc+cKjt/18Tu0dmMRGQ7us0nz9IHhKWNphyGvsnpFb/Wrk75+F+k8nlwhsl2Z3cHEF18chOqwJhbK8z3fhZCs9w1sVuksd9+KS6GX4kJ09G/6fUGtWjnfk26L/UvXv8xjtrs+S4l9qvp0xQbVfvaWz9bz6qV1qqe1CTmXe8F9kxywZK/wEREmVa8+cOTUg+hAxKx2Z2MPe7D6R62/UkZRxFer75Z0FX2T5wdwikp+xGTiUaFkF6aKbdZNx/QeXWm4Sb/+aoAM6YfjHAowq+XN9n78s8OoaMIlaT8/Yq0GrwOFAoWs3NZjdPcu5d9KH1AFhQWXaHSPW2d4gP1EH0Xga+DKfsaqXEWVg8FPu1tH5N3rNbji5oZgTao0kPPCJNvZkPpPNR4YVvewyCCTOxZIbJ01yjuBwFlbJIc/s4Ks0ql14hGbAkegD5F+r2Ca3uPLoOl3+3GUU8KWtRy0kZWUrZYvdB2DY7P50yN66HlXfme/J4EXhUUF/eC/yCD/9l0y3iIP/cg4rYtiUkZr35kwSYWTWkBpk="

addons:
  apt:
    packages:
      - npm

matrix:
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6

install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
- coverage run -m pytest -s --doctest-modules --verbose --durations=10 --pyargs afqbrowser
- |
    if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
      npm install -g jsdoc
      pip install sphinx sphinx-gallery pillow sphinx-js numpydoc
      # Doctr for gh-pages;
      set -e;
      pip install doctr;
      cd doc;
      make html;
      cd ..;
      doctr deploy --built-docs doc/_build/html .;
    fi
